# -*- coding: utf-8 -*-
"""Student Mental Health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZz3HRRpDyAmArka9i7QZ2-Nx0TywCuw
"""

!pip install optuna catboost

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import optuna
import catboost
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    f1_score,
    roc_curve,
    auc,
    precision_recall_curve
)
from catboost import CatBoostClassifier, Pool

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

df=pd.read_csv('/content/gdrive/My Drive/studentdepression.csv')
df.head()

print("-")
print(df.info())
print("-")
print(df.isnull().sum())
print("-")
print(df.describe())

target = 'Depression'

bar_cols = df.select_dtypes(include = ['object', 'category']).columns.drop(target, errors = 'ignore')

b_features = len(bar_cols)
b_cols = 2
b_rows = (b_features + b_cols - 1) // b_cols

fig, axes = plt.subplots(b_rows, b_cols, figsize = (12, b_rows*3))
axes = axes.flatten()

for i, col in enumerate(bar_cols):
    counts = (
        df.groupby([col, target]).size().reset_index(name = 'count')
    )

    sns.barplot(
        x=col,
        y = 'count',
        hue = target,
        data = counts,
        ax = axes[i]
    )
    axes[i].set_title(f"Barplot of {col} by {target}")
    axes[i].set_xlabel(col)
    axes[i].set_ylabel("Count")
    axes[i].tick_params(axis='x', rotation=45)
    axes[i].legend(title=target)

for j in range(i + 1, len(axes)):
    axes[j].axis('off')

plt.tight_layout()
plt.show()

cat_cols = df.select_dtypes(include = ['object', 'category']).columns.drop(target, errors = 'ignore')

c_features = len(cat_cols)
c_cols = 2
c_rows = (c_features + c_cols - 1) // c_cols

figc, axesc = plt.subplots(c_rows, c_cols, figsize = (12, c_rows*3))
axesc = axesc.flatten()

for i, col in enumerate(bar_cols):
    sns.countplot(
        x=col,
        hue = target,
        data = df,
        ax = axesc[i],
        palette='Set2'
    )
    axesc[i].set_title(f"Countplot of {col} by {target}")
    axesc[i].set_xlabel(col)
    axesc[i].set_ylabel("Count")
    axesc[i].tick_params(axis='x', rotation=45)
    axesc[i].legend(title=target)

for j in range(i + 1, len(axesc)):
    axesc[j].axis('off')

plt.tight_layout()
plt.show()

num_cols = df.select_dtypes(include = np.number).columns.drop(target, errors = 'ignore')

n_features = len(num_cols)
n_cols = 2
n_rows = (n_features + n_cols - 1) // n_cols

fign, axesn = plt.subplots(n_rows, n_cols, figsize = (12, n_rows*3))
axesn = axesn.flatten()

for i, col in enumerate(num_cols):
    sns.histplot(
        x = col,
        kde = True,
        data = df,
        ax = axesn[i]
    )
    axesn[i].set_title(f"Distribution of {col}")
    axesn[i].set_xlabel(col)
    axesn[i].set_ylabel("Count")
    axesn[i].tick_params(axis='x', rotation=45)

for j in range(i + 1, len(axesn)):
    axesn[j].axis('off')

plt.tight_layout()
plt.show()

#droping cols which have no contribution
#Here everyone is student so profession doesnt make sense
#work pressure and job statisfication are 99% imbalanced
cols_to_drop = ['id', 'Profession', 'Work Pressure', 'Job Satisfaction']

df.drop(cols_to_drop, axis = 1, inplace = True)
df.head()

# converting sleep duration to int
temp = df['Sleep Duration'].str.extract(r'(\d+)-(\d+)')

temp = temp.apply(pd.to_numeric, errors = 'coerce')

df['Sleep Duration int'] = (
    temp.mean(axis = 1)
        .round()
        .fillna(0)
        .astype(int)

)

medain_val = df.loc[df['Sleep Duration int'] != 0, 'Sleep Duration int'].median()
df['Sleep Duration int'] = df['Sleep Duration int'].replace(0, medain_val)
df.drop(['Sleep Duration'], axis = 1, inplace = True)

df.head()

box_cols = df.select_dtypes(include = np.number).columns.drop(target, errors = 'ignore')

plt.figure(figsize=(12, 8))
sns.boxplot(data = df[box_cols])
plt.tight_layout()
plt.show()

X = df.drop(['Depression'], axis = 1)
y = df['Depression']

cate_cols = X.select_dtypes(include = ['object', 'category']).columns.tolist()
cat_cols = list(cat_cols)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify=y)

"""#CatBoostClassifier"""

from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, classification_report, confusion_matrix

# Detect categorical columns
cat_cols = list(X_train.select_dtypes(include=['object', 'category']).columns)
print("Categorical cols used:", cat_cols)

# Get column indices (CatBoost needs index, not names)
cat_features_idx = [X_train.columns.get_loc(col) for col in cat_cols]

# Initialize CatBoost model
cat_model = CatBoostClassifier(
    iterations=2000,
    learning_rate=0.03,
    depth=6,
    eval_metric='AUC',
    random_seed=42,
    verbose=200
)

# Train model
cat_model.fit(
    X_train,
    y_train,
    cat_features=cat_features_idx,
    eval_set=(X_test, y_test),
    use_best_model=True
)

# Predictions
y_proba = cat_model.predict_proba(X_test)[:, 1]
y_pred = (y_proba >= 0.5).astype(int)

# Metrics
print("Validation metrics:")
print("ROC AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

print("\nClassification report:\n", classification_report(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f'ROC AUC = {roc_auc:.3f}')
plt.plot([0,1],[0,1],'k--')
plt.xlabel('FPR'); plt.ylabel('TPR'); plt.title('ROC Curve'); plt.legend(); plt.show()

# PR-curve
p, r, _ = precision_recall_curve(y_test, y_proba)
plt.figure(figsize=(6,5))
plt.plot(r, p)
plt.xlabel('Recall'); plt.ylabel('Precision'); plt.title('Precision-Recall Curve'); plt.show()

import tqdm

target = 'Depression'
N_SPLITS = 5
RANDOM_STATE = 42
SAVE_BEST_MODEL = True
MODEL_SAVE_PREFIX = "catboost_fold"

CB_PARAMS = dict(
    iterations=2000,
    learning_rate=0.03,
    depth=6,
    eval_metric='AUC',
    random_seed=RANDOM_STATE,
    early_stopping_rounds=50,
    verbose=100,
    task_type='CPU'
)

X = df.drop(columns=[target]).copy()
y = df[target].copy()

skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
oof_preds = np.zeros(len(X))
oof_labels = y.values
fold_metrics = []
feature_importances = []
models = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), 1):
    print(f"\n=== Fold {fold} ===")
    X_tr, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
    y_tr, y_val = y.iloc[train_idx].copy(), y.iloc[val_idx].copy()

    cat_cols = list(X_tr.select_dtypes(include=['object', 'category']).columns)
    print("Categorical cols used:", cat_cols)

    num_cols = X_tr.select_dtypes(include=['number']).columns.tolist()
    if len(num_cols) > 0:
        X_tr[num_cols] = X_tr[num_cols].fillna(X_tr[num_cols].median())
        X_val[num_cols] = X_val[num_cols].fillna(X_tr[num_cols].median())

    if len(cat_cols) > 0:
        X_tr[cat_cols] = X_tr[cat_cols].fillna('missing').astype(str)
        X_val[cat_cols] = X_val[cat_cols].fillna('missing').astype(str)

    train_pool = Pool(X_tr, y_tr, cat_features=cat_cols)
    val_pool   = Pool(X_val, y_val, cat_features=cat_cols)

    final_model = CatBoostClassifier(**CB_PARAMS)
    final_model.fit(train_pool, eval_set=val_pool, use_best_model=True)

    val_preds = final_model.predict_proba(X_val)[:, 1]
    oof_preds[val_idx] = val_preds

    y_pred_label = (val_preds >= 0.5).astype(int)
    auc = roc_auc_score(y_val, val_preds)
    acc = accuracy_score(y_val, y_pred_label)
    f1 = f1_score(y_val, y_pred_label)
    print(f"Fold {fold} AUC: {auc:.6f}  Acc: {acc:.4f}  F1: {f1:.4f}")
    print("Confusion matrix:\n", confusion_matrix(y_val, y_pred_label))
    fold_metrics.append({'fold': fold, 'auc': auc, 'acc': acc, 'f1': f1})

    try:
        fi = pd.Series(final_model.get_feature_importance(), index=X_tr.columns).sort_values(ascending=False)
    except Exception:
        fi = pd.Series(final_model.get_feature_importance(type='PredictionValuesChange'), index=X_tr.columns).sort_values(ascending=False)
    feature_importances.append(fi)

    models.append(final_model)


oof_auc = roc_auc_score(oof_labels, oof_preds)
print("\n=== CV Summary ===")
print("OOF ROC AUC:", oof_auc)

metrics_df = pd.DataFrame(fold_metrics)
print("\nPer-fold metrics:\n", metrics_df)
print("\nMean ± std:")
print(metrics_df[['auc','acc','f1']].agg(['mean','std']).T)

fi_df = pd.concat(feature_importances, axis=1).fillna(0)
fi_df.columns = [f"fold_{i+1}" for i in range(len(feature_importances))]
fi_df['mean_importance'] = fi_df.mean(axis=1)
fi_df = fi_df.sort_values('mean_importance', ascending=False)
print("\nTop features by mean importance:\n", fi_df['mean_importance'].head(20))

oof_df = pd.DataFrame({'y_true': oof_labels, 'y_pred_proba': oof_preds})

cv_results = {
    'metrics_df': metrics_df,
    'oof_auc': oof_auc,
    'oof_df': oof_df,
    'feature_importances_df': fi_df,
    'models': models
}

print("===== FINAL MODEL PERFORMANCE =====")
print("ROC AUC Score :", roc_auc_score(y_test, y_proba))
print("Accuracy      :", accuracy_score(y_test, y_pred))
print("F1 Score      :", f1_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("CatBoost Confusion Matrix")
plt.show()

"""#RandomForestClassifier"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, classification_report, confusion_matrix

# Detect categorical columns
cat_cols = list(X_train.select_dtypes(include=['object', 'category']).columns)
print("Categorical cols used:", cat_cols)

# Preprocessing (One-Hot Encoding for categorical features)
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)

# Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

# Pipeline
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', rf_model)
])

# Train model
model.fit(X_train, y_train)

# Predictions
y_proba = model.predict_proba(X_test)[:,1]
y_pred = (y_proba >= 0.5).astype(int)

# Metrics
print("Validation metrics:")
print("ROC AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

print("\nClassification report:\n", classification_report(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

# Plot
plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['No Depression','Depression'],
    yticklabels=['No Depression','Depression']
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - Random Forest")
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve, auc, precision_recall_curve
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt

# Detect categorical columns
cat_cols = X_train.select_dtypes(include=['object']).columns

# Encoder
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)

# Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

# Pipeline
model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('classifier', rf_model)
])

# Train model
model.fit(X_train, y_train)

# Probability prediction
y_proba = model.predict_proba(X_test)[:,1]

# ================= ROC Curve =================
fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f'ROC AUC = {roc_auc:.3f}')
plt.plot([0,1],[0,1],'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Random Forest')
plt.legend()
plt.show()

# ================= Precision Recall Curve =================
precision, recall, _ = precision_recall_curve(y_test, y_proba)

plt.figure(figsize=(6,5))
plt.plot(recall, precision)
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve - Random Forest')
plt.show()

"""#Support Vector Machine Classifier"""

from sklearn.svm import SVC
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score, classification_report, confusion_matrix

# Detect categorical columns
cat_cols = list(X_train.select_dtypes(include=['object', 'category']).columns)
print("Categorical cols used:", cat_cols)

# Preprocessing (Encode categorical columns)
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)

# Support Vector Machine Model
svm_model = SVC(
    kernel='rbf',
    probability=True,
    random_state=42
)

# Pipeline
model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('classifier', svm_model)
])

# Train Model
model.fit(X_train, y_train)

# Predictions
y_proba = model.predict_proba(X_test)[:,1]
y_pred  = (y_proba >= 0.5).astype(int)

# Evaluation
print("Validation metrics:")
print("ROC AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

print("\nClassification report:\n", classification_report(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot heatmap
plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['No Depression','Depression'],
    yticklabels=['No Depression','Depression']
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - SVM")
plt.show()

from sklearn.metrics import roc_curve, auc, precision_recall_curve
import matplotlib.pyplot as plt

# ================= ROC Curve =================
fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

# ================= PR Curve =================
precision, recall, _ = precision_recall_curve(y_test, y_proba)

# Plot both curves
plt.figure(figsize=(12,5))

# ROC Curve
plt.subplot(1,2,1)
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.3f}')
plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - SVM")
plt.legend()

# Precision Recall Curve
plt.subplot(1,2,2)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve - SVM")

plt.tight_layout()
plt.show()

"""#Logistic Regression classifier"""

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score, classification_report, confusion_matrix

# Detect categorical columns
cat_cols = list(X_train.select_dtypes(include=['object', 'category']).columns)
print("Categorical cols used:", cat_cols)

# Encode categorical variables
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)

# Logistic Regression Model
log_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Pipeline
model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('classifier', log_model)
])

# Train model
model.fit(X_train, y_train)

# Predictions
y_proba = model.predict_proba(X_test)[:,1]
y_pred  = (y_proba >= 0.5).astype(int)

# Evaluation
print("Validation metrics:")
print("ROC AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

print("\nClassification report:\n", classification_report(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Create Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n", cm)

# Plot Heatmap
plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['No Depression','Depression'],
    yticklabels=['No Depression','Depression']
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

from sklearn.metrics import roc_curve, auc, precision_recall_curve
import matplotlib.pyplot as plt

# ROC values
fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

# Precision Recall values
precision, recall, _ = precision_recall_curve(y_test, y_proba)

# Plot both curves
plt.figure(figsize=(12,5))

# ROC Curve
plt.subplot(1,2,1)
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.3f}')
plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Logistic Regression")
plt.legend()

# Precision-Recall Curve
plt.subplot(1,2,2)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve - Logistic Regression")

plt.tight_layout()
plt.show()

"""#DecisionTreeClassifier"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score, classification_report, confusion_matrix

# Detect categorical columns
cat_cols = list(X_train.select_dtypes(include=['object', 'category']).columns)
print("Categorical cols used:", cat_cols)

# Encode categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)

# Decision Tree Model
dt_model = DecisionTreeClassifier(
    max_depth=6,
    random_state=42
)

# Pipeline
model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('classifier', dt_model)
])

# Train Model
model.fit(X_train, y_train)

# Predictions
y_proba = model.predict_proba(X_test)[:,1]
y_pred  = (y_proba >= 0.5).astype(int)

# Evaluation
print("Validation metrics:")
print("ROC AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

print("\nClassification report:\n", classification_report(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Create Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n", cm)

# Plot Heatmap
plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['No Depression','Depression'],
    yticklabels=['No Depression','Depression']
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - Decision Tree")
plt.show()

from sklearn.metrics import roc_curve, auc, precision_recall_curve
import matplotlib.pyplot as plt

# ROC values
fpr, tpr, _ = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

# Precision-Recall values
precision, recall, _ = precision_recall_curve(y_test, y_proba)

# Plot both curves
plt.figure(figsize=(12,5))

# ROC Curve
plt.subplot(1,2,1)
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.3f}')
plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Decision Tree")
plt.legend()

# Precision-Recall Curve
plt.subplot(1,2,2)
plt.plot(recall, precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve - Decision Tree")

plt.tight_layout()
plt.show()

